version: '3'

services:
  app:
    build: .
    depends_on:
      - 'database'
    ports:
      - '3003:3003'
    volumes:
      - '.:/src/app/'
      - '/src/app/node_modules'
    command: 'npm start & npm run db:setup'

  database:
    image: mongo:latest
    ports:
      - '27017:27017'