version: 2.1
dependencies:
  cache_directories:
    - mongodb-linux-x86_64-ubuntu1204-3.2.0
  pre:
    - sudo stop service mongod
    - sudo cp mongodb-linux-x86_64-ubuntu1204-3.2.0/bin/* /usr/bin
    - sudo start service mongod
orbs:
  node: circleci/node@1.1.6
machine:
  services:
    - mongodb
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm start
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test